version: '3.6'
services:
  yii_demo:
    build:
      ./php
    ports:
    - "80:80"
    depends_on:
    - mysql
    links:
    - mysql
    volumes:
    - ./yii_demo:/var/www/html

  mysql:
    image: mariadb:${MARIADB_VERSION:-latest}
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_DATABASE=yii

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin:${PHPMYADMIN_VERSION:-latest}
    container_name: ${COMPOSE_PROJECT_NAME}_phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
      UPLOAD_LIMIT: 20M

